routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/admin/panel');
});

Auth::routes();



Route::get('/user/active/email/{token}','Admin\UserController@activation')->name('activation.account');


Route::get('/home', 'HomeController@index')->name('home');
Route::get('/admin/panel/athen', 'Admin\UserController@athenticationindex2')->name('users.athen');
Route::get('/admin/panel/usersecreport', 'Admin\UserController@usersecreport')->name('users.usersecreport');
Route::get('/admin/panel/modirsecreport', 'Admin\UserController@modirsecreport')->name('users.modirsecreport');
Route::get('/admin/panel/transaction', 'user\BuyController@transaction');
Route::get('/admin/panel/order', 'user\BuyController@order');
$this->get('/admin/panel/ticket', 'user\TicketController@index2');
$this->get('/admin/panel/sale', 'user\SaleController@indexadmin');
$this->get('/admin/panel/buy', 'user\BuyController@indexadmin');
$this->get('/admin/panel/voucher', 'user\VoucherController@indexadmin');
Route::delete('admin/panel/adminticket/{id}', 'user\TicketController@destroy2')->name('adminticket.delete');
Route::post('admin/panel/verify/{id}', 'user\TicketController@verify')->name('adminticket.verify');
Route::post('admin/panel/buyverify/{id}', 'user\BuyController@verify')->name('buy.verify');
Route::post('admin/panel/saleverify/{id}', 'user\SaleController@verify')->name('sale.verify');
Route::post('admin/panel/userverify/{id}', 'Admin\UserController@verify')->name('user.verify');
Route::post('admin/panel/userverify2/{id}', 'Admin\UserController@verify2')->name('user.verify2');
Route::get('/admin/panel/account', 'user\AccountInformationController@indexadmin');
Route::delete('/admin/panel/delaccount/{id}', 'user\AccountInformationController@destroy2')->name('delaccount');
Route::post('/admin/panel/verifyaccount/{id}', 'user\AccountInformationController@verifyaccount')->name('verifyaccount');
Route::delete('/admin/panel/adminsale/{id}', 'user\SaleController@destroy2')->name('adminsale.delete');
Route::delete('/admin/panel/adminbuy/{id}', 'user\BuyController@destroy2')->name('adminbuy.delete');
Route::post('/admin/panel/updatepass', 'Admin\UserController@updatepass')->name('users.updatepass');





Route::group(['namespace' => 'Admin'   ,  'middleware' => ['auth','checkAdmin'], 'prefix' => 'admin'],function () {
    $this->get('/panel', 'PanelController@index');
    $this->resource('/panel/users', 'UserController');
    $this->resource('/panel/modir', 'AdminController');
    $this->resource('/panel/setting', 'GeneralsettingController');
    $this->resource('/panel/managingcurrency' , 'ManagingCurrencyController');
    $this->resource('/panel/statusbuysale' , 'StatusBuySaleController');
    $this->resource('/panel/notifsetting' , 'NotifSettingController');
    $this::resource('/panel/bank' , 'BankController');
    });




$this->get('/user/panel', 'Admin\PanelController@index2');
Route::get('/user/panel/transaction', 'user\BuyController@transaction2');
Route::get('/user/panel/profile', 'Admin\UserController@profile');
Route::patch('/user/panel/profile', 'Admin\UserController@updateprofile')->name('profile.update');
Route::get('/user/panel/senddocuments', 'Admin\UserController@senddocuments');
Route::patch('/user/panel/senddocuments', 'Admin\UserController@updatesenddocuments')->name('senddocuments.update');;
Route::patch('/user/panel/updatesenddocuments', 'Admin\UserController@updatesenddocuments');
Route::get('/user/panel/resetpassword', 'Admin\UserController@resetpassword');
Route::post('/user/panel/salepayment', 'User\SaleController@payment')->name('salepayment');
Route::get('/user/panel/payment/checker', 'User\SaleController@checker');
Route::post('/user/panel/buypayment', 'User\BuyController@payment')->name('buypayment');
Route::get('/user/panel/payment/checker', 'User\BuyController@checker');
Route::post('/user/panel/voucherpayment', 'User\VoucherController@payment')->name('voucherpayment');
Route::get('/user/panel/payment/voucherpayment', 'User\VoucherController@checker');


Route::group(['namespace' => 'User'  , 'prefix' => 'user'],function () {

    $this->resource('/panel/userpanel', 'UserpanelController');
    $this->resource('/panel/ticket', 'TicketController');
    $this->resource('/panel/accountinformation', 'AccountInformationController');
    $this->resource('/panel/sale', 'SaleController');
    $this->resource('/panel/buy', 'BuyController');
    $this->resource('/panel/voucher', 'VoucherController');
});






Route::group(['namespace' => 'Auth'] , function (){
    // Authentication Routes...
    $this->get('login', 'LoginController@showLoginForm')->name('login');
    $this->post('login', 'LoginController@login');
    $this->get('logout', 'LoginController@logout')->name('logout');

    // Login And Register With Google
    // $this->get('login/google', 'LoginController@redirectToProvider');
    // $this->get('login/google/callback', 'LoginController@handleProviderCallback');
    // Registration Routes...
    $this->get('register', 'RegisterController@showRegistrationForm')->name('register');
    $this->post('register', 'RegisterController@register');

    // Password Reset Routes...
    $this->get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    $this->post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    $this->get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    $this->post('password/reset', 'ResetPasswordController@reset');
});

app/generalsetting.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class generalsetting extends Model
{

    protected $fillable = [
        'sitename','companyname','supportemail','adminemail',
        'tell','phone','addresscompany','countbuy_day','intercambios_day',
        'logo',

    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */



}

app/Http/Controllers/Admin/GeneralsettingController.php
<?php

namespace App\Http\Controllers\Admin;

use App\generalsetting;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class GeneralsettingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('Admin.GeneralSetting.GeneralSetting');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $value=$request->all();




        if ( $request->hasFile('companylogo') ) {
            $FileName = time() . '.' . $request->file('companylogo')->getClientOriginalExtension();
            if ($request->file('companylogo')->move('assets/companylogo', $FileName)) {

                //  dd($FileName);

                $value['logo'] = $FileName;

            }

        }
       // dd($value);
        $value = generalsetting::create($value);
         // return redirect(route('setting'));
        alert()->success('', ' عملیات با موفقیت انجام شد ')->persistent('Close');
        return back();
    }


        /*$value=$request->all();
        GeneralsettingController::create($value);
        return back();*/


    /**
     * Display the specified resource.
     *
     * @param  \App\generalsetting  $generalsetting
     * @return \Illuminate\Http\Response
     */
    public function show(generalsetting $generalsetting)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\generalsetting  $generalsetting
     * @return \Illuminate\Http\Response
     */
    public function edit(generalsetting $generalsetting)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\generalsetting  $generalsetting
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, generalsetting $generalsetting)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\generalsetting  $generalsetting
     * @return \Illuminate\Http\Response
     */
    public function destroy(generalsetting $generalsetting)
    {
        //
    }
}

resources/views/Admin/GeneralSetting/GeneralSetting.blade.php
@extends('Admin.master')

@section('script')

@endsection

@section('content')
    <div class="col-md-12">

        <!--begin::Portlet-->
        <div class="m-portlet m-portlet--tab">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                    <span class="m-portlet__head-icon m--hide">
                        <i class="la la-gear"></i>
                    </span>
                        <h3 class="m-portlet__head-text">
                            تنظیمات عمومی
                        </h3>
                    </div>
                </div>
            </div>

            <!--begin::Form-->
            <form class="form-horizontal" action="{{ route('setting.store') }}" method="post" enctype="multipart/form-data">
                {{ csrf_field() }}
                <div class="m-portlet__body">
                    <div class="container p-0">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group m-form__group">
                                    <label for="sitename" class="control-label">نام سایت:</label>
                                    <input type="text" class="form-control" name="sitename" id="sitename" placeholder="خرید و فروش اتوماتیک ارز های دیجیتال" value="{{ old('sitename') }}">
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group m-form__group">
                                    <label for="companyname" class="control-label">نام کمپانی :</label>
                                    <input type="text" class="form-control" name="companyname" id="companyname" placeholder="زرین اکسچنج شما" value="{{ old('companyname') }}">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group m-form__group">
                                    <label for="supportemail" class="control-label">ایمیل پشتیبانی :</label>
                                    <input type="text" class="form-control" name="supportemail" id="supportemail" placeholder="ایمیل پشتیبانی را وارد کنید" value="{{ old('supportemail') }}">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group m-form__group">
                                    <label for="adminemail" class="control-label">ایمیل مدیریت :</label>
                                    <input type="text" class="form-control" name="adminemail" id="adminemail" placeholder="ایمیل مدیریت را وارد کنید" value="{{ old('adminemail') }}">
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group m-form__group">
                                    <label for="tell" class="control-label">تلفن ثابت :</label>
                                    <input type="text" class="form-control" name="tell" id="tell" placeholder="تلفن ثابت را وارد کنید" value="{{ old('tell') }}">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group m-form__group">
                                    <label for="phone" class="control-label">تلفن همراه</label>
                                    <input type="text" class="form-control" name="phone" id="phone" placeholder="تلفن همراه خود را وارد کنید" value="{{ old('phone') }}">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group m-form__group">
                                    <label for="addresscompany" class="control-label">آدرس کمپانی :</label>
                                    <input type="text" class="form-control" name="addresscompany" id="addresscompany" placeholder="آدرس کمپانی را وارد کنید" value="{{ old('addresscompany') }}">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group m-form__group">
                                    <label for="countbuy_day" class="control-label">تعداد خرید روزانه :</label>
                                    <input type="text" class="form-control" name="countbuy_day" id="countbuy_day" placeholder="سقف تعداد سفارش مجاز روزانه هر کاربر" value="{{ old('countbuy_day') }}">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group m-form__group">
                                    <label for="intercambios_day" class="control-label">سقف تبادل ریالی روزانه :</label>
                                    <input type="text" class="form-control" name="intercambios_day" id="intercambios_day" placeholder="سقف تبادل ریالی روزانه" value="{{ old('intercambios_day') }}">
                                </div>
                            </div>
                           {{-- <div class="col-lg-8">
                                <div class="fileupload fileupload-new" data-provides="fileupload">

                                    <div>

                            <span class="btn btn-file "><span class="fileupload-new"> لوگو کمپانی   : </span>
                                <input type="file" name="companylogo" /></span>

                                    </div>
                                </div>
                            </div>--}}
                            <div class="form-group">
                                <label class="col-md-8 control-label"></i>لوگو کمپانی   : </label>
                                <div class="input-group input-group-sm">
                                    <input name="companylogo" class="" type="file" required
                                    >
                                    <br>
                                </div>
                            </div>










                        </div>
                    </div>
                </div>







                <div class="m-portlet__foot">
                    <div class="m-form__actions">
                        <button type="submit" class="btn btn-success">ویرایش تنظیمات عمومی</button>

                    </div>
                </div>
            </form>

            <!--end::Form-->
        </div>

        <!--end::Portlet-->


    </div>

@endsection