routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/admin/panel');
});

Auth::routes();



Route::get('/user/active/email/{token}','Admin\UserController@activation')->name('activation.account');


Route::get('/home', 'HomeController@index')->name('home');
Route::get('/admin/panel/athen', 'Admin\UserController@athenticationindex2')->name('users.athen');
Route::get('/admin/panel/usersecreport', 'Admin\UserController@usersecreport')->name('users.usersecreport');
Route::get('/admin/panel/modirsecreport', 'Admin\UserController@modirsecreport')->name('users.modirsecreport');
Route::get('/admin/panel/transaction', 'user\BuyController@transaction');
Route::get('/admin/panel/order', 'user\BuyController@order');
$this->get('/admin/panel/ticket', 'user\TicketController@index2');
$this->get('/admin/panel/sale', 'user\SaleController@indexadmin');
$this->get('/admin/panel/buy', 'user\BuyController@indexadmin');
$this->get('/admin/panel/voucher', 'user\VoucherController@indexadmin');
Route::delete('admin/panel/adminticket/{id}', 'user\TicketController@destroy2')->name('adminticket.delete');
Route::post('admin/panel/verify/{id}', 'user\TicketController@verify')->name('adminticket.verify');
Route::post('admin/panel/buyverify/{id}', 'user\BuyController@verify')->name('buy.verify');
Route::post('admin/panel/saleverify/{id}', 'user\SaleController@verify')->name('sale.verify');
Route::post('admin/panel/userverify/{id}', 'Admin\UserController@verify')->name('user.verify');
Route::post('admin/panel/userverify2/{id}', 'Admin\UserController@verify2')->name('user.verify2');
Route::get('/admin/panel/account', 'user\AccountInformationController@indexadmin');
Route::delete('/admin/panel/delaccount/{id}', 'user\AccountInformationController@destroy2')->name('delaccount');
Route::post('/admin/panel/verifyaccount/{id}', 'user\AccountInformationController@verifyaccount')->name('verifyaccount');
Route::delete('/admin/panel/adminsale/{id}', 'user\SaleController@destroy2')->name('adminsale.delete');
Route::delete('/admin/panel/adminbuy/{id}', 'user\BuyController@destroy2')->name('adminbuy.delete');
Route::post('/admin/panel/updatepass', 'Admin\UserController@updatepass')->name('users.updatepass');





Route::group(['namespace' => 'Admin'   ,  'middleware' => ['auth','checkAdmin'], 'prefix' => 'admin'],function () {
    $this->get('/panel', 'PanelController@index');
    $this->resource('/panel/users', 'UserController');
    $this->resource('/panel/modir', 'AdminController');
    $this->resource('/panel/setting', 'GeneralsettingController');
    $this->resource('/panel/managingcurrency' , 'ManagingCurrencyController');
    $this->resource('/panel/statusbuysale' , 'StatusBuySaleController');
    $this->resource('/panel/notifsetting' , 'NotifSettingController');
    $this::resource('/panel/bank' , 'BankController');
    });




$this->get('/user/panel', 'Admin\PanelController@index2');
Route::get('/user/panel/transaction', 'user\BuyController@transaction2');
Route::get('/user/panel/profile', 'Admin\UserController@profile');
Route::patch('/user/panel/profile', 'Admin\UserController@updateprofile')->name('profile.update');
Route::get('/user/panel/senddocuments', 'Admin\UserController@senddocuments');
Route::patch('/user/panel/senddocuments', 'Admin\UserController@updatesenddocuments')->name('senddocuments.update');;
Route::patch('/user/panel/updatesenddocuments', 'Admin\UserController@updatesenddocuments');
Route::get('/user/panel/resetpassword', 'Admin\UserController@resetpassword');
Route::post('/user/panel/salepayment', 'User\SaleController@payment')->name('salepayment');
Route::get('/user/panel/payment/checker', 'User\SaleController@checker');
Route::post('/user/panel/buypayment', 'User\BuyController@payment')->name('buypayment');
Route::get('/user/panel/payment/checker', 'User\BuyController@checker');
Route::post('/user/panel/voucherpayment', 'User\VoucherController@payment')->name('voucherpayment');
Route::get('/user/panel/payment/voucherpayment', 'User\VoucherController@checker');


Route::group(['namespace' => 'User'  , 'prefix' => 'user'],function () {

    $this->resource('/panel/userpanel', 'UserpanelController');
    $this->resource('/panel/ticket', 'TicketController');
    $this->resource('/panel/accountinformation', 'AccountInformationController');
    $this->resource('/panel/sale', 'SaleController');
    $this->resource('/panel/buy', 'BuyController');
    $this->resource('/panel/voucher', 'VoucherController');
});






Route::group(['namespace' => 'Auth'] , function (){
    // Authentication Routes...
    $this->get('login', 'LoginController@showLoginForm')->name('login');
    $this->post('login', 'LoginController@login');
    $this->get('logout', 'LoginController@logout')->name('logout');

    // Login And Register With Google
    // $this->get('login/google', 'LoginController@redirectToProvider');
    // $this->get('login/google/callback', 'LoginController@handleProviderCallback');
    // Registration Routes...
    $this->get('register', 'RegisterController@showRegistrationForm')->name('register');
    $this->post('register', 'RegisterController@register');

    // Password Reset Routes...
    $this->get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    $this->post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    $this->get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    $this->post('password/reset', 'ResetPasswordController@reset');
});

app/voucher.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class voucher extends Model
{
    //
    protected $fillable = [
        'user_id','voucher_type','voucher_number','voucher_code',
        'price_rial','price_arz','status',


    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/User/VoucherController.php
<?php

namespace App\Http\Controllers\user;

use App\Http\Controllers\Controller;
use App\ManagingCurrency;
use App\User;
use App\voucher;
use Illuminate\Http\Request;
use SoapClient;


class VoucherController extends Controller
{
    protected $MerchantID = 'f83cc956-f59f-11e6-889a-005056a205be';
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('user.voucher.listvoucher');
    }
    public function indexadmin()
    {
        $values=voucher::latest()->paginate(12);
        //  dd($values->toArray()); die;
        $user_id=$values[0]['user_id'];
        // dd($test);die;
        $users=User::where('id',$user_id)->get();
      //   dd($values);
        return view('Admin.voucher.index',compact('values','users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $price=ManagingCurrency::get();
        //  dd($price[0]);
        $cards=\App\account_information::where('user_id',auth()->user()->id)->get();
        $i=0;
        return view('user.voucher.voucher_buy' , compact('price','cards' , 'i'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        dd($request->all());
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\voucher  $voucher
     * @return \Illuminate\Http\Response
     */
    public function show(voucher $voucher)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\voucher  $voucher
     * @return \Illuminate\Http\Response
     */
    public function edit(voucher $voucher)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\voucher  $voucher
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, voucher $voucher)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\voucher  $voucher
     * @return \Illuminate\Http\Response
     */
    public function destroy(voucher $voucher)
    {
        //
    }

    public function payment()
    {

        $Amount = 100; //Amount will be based on Toman - Required
        $Description = 'توضیحات تراکنش تستی'; // Required
        $Email = auth()->user()->email; // Optional
        $Mobile = '09123456789'; // Optional
        $CallbackURL = 'http://localhost:8000/user/panel/sale/checker'; // Required


        $client = new SoapClient('https://www.zarinpal.com/pg/services/WebGate/wsdl', ['encoding' => 'UTF-8']);

        $result = $client->PaymentRequest(
            [

                'MerchantID' => $this->MerchantID,
                'Amount' => $Amount,
                'Description' => $Description,
                'Email' => $Email,
                'Mobile' => $Mobile,
                'CallbackURL' => $CallbackURL,
            ]
        );

        if ($result->Status == 100) {

            auth()->user()->buy()->create([
                'resnumber'=> $result->Authority,
                'currency_required'=> 1,
                'currency_number'=>2,
                'accountـreceived'=>3,
                'total_price'=>4,
                'orderـtype'=>'5',
                'state'=>'6',

            ]);

            return redirect('https://www.zarinpal.com/pg/StartPay/'.$result->Authority);
        } else {
            echo'ERR: '.$result->Status;
        }
    }
    public function checker()
    {
        $Authority=request('Authority');
        $payment=sale::whereResnumber($Authority)->firstOrFaild();
        if (request('Status') == 'OK') {

            $client = new SoapClient('https://www.zarinpal.com/pg/services/WebGate/wsdl', ['encoding' => 'UTF-8']);

            $result = $client->PaymentVerification(
                [
                    'MerchantID' => $this->MerchantID,
                    'Authority' => $Authority,
                    'Amount' => $payment->price,
                ]
            );
            if ($result->Status == 100) {
                echo 'Transaction success. RefID:'.$result->RefID;
            } else {
                echo 'Transaction failed. Status:'.$result->Status;
            }
        } else {
            echo 'Transaction canceled by user';


        }
    }
}

resources/views/Admin/voucher/index.blade.php
@extends('Admin.master')

@section('content')
    <div class="m-portlet m-portlet--tab">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <span class="m-portlet__head-icon m--hide">
                        <i class="la la-gear"></i>
                    </span>
                    <h3 class="m-portlet__head-text">
                        سفارشات ووچر
                    </h3>
                </div>
            </div>
        </div>
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <div class="page-header head-section">

            <div class="btn-group">


                <!--
                      comment
                -->

            </div>
        </div>
        <div class="table-responsive">
            <table class="table table-striped table-bordered">
                <thead>
                <tr>
                    <th>شناسه</th>
                    <th>خریدار</th>
                    <th>شماره ووچر</th>
                    <th>کد ووچر</th>
                    <th>مبلغ ریالی</th>
                    <th>مبلغ ارزی</th>
                    <th>تاریخ</th>
                    <th>وضعیت</th>
                    <th>مدیریت</th>
                </tr>
                </thead>
                <tbody>
                @foreach($values as $value)
                    <tr>
                        <td>{{ $value->id }}</td>
                             @foreach($users as $user)
                                <td>{{ $user->name }}</td>
                             @endforeach

                                <td>{{ $value->voucher_number }}</td>
                                <td>{{ $value->voucher_code }}</td>
                                <td>{{ $value->price_rial }}</td>
                                <td>{{ $value->price_arz }}</td>
                                <td>{{ $value->created_at }}</td>
                                <td>{{ $value->status }}</td>

                        <td>
                            <form action="{{ route('buy.destroy'  , ['id' => $value->id]) }}" method="post">
                                {{ method_field('delete') }}
                                {{ csrf_field() }}
                                <div class="btn-group btn-group-xs">
                                    <button type="submit" class="btn btn-danger">حذف</button>
                                </div>
                            </form>
                        </td>
                    </tr>
                @endforeach


                </tbody>
            </table>
        </div>
        <div style="text-align: center">

        </div>
    </div>
    </div>
@endsection