routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/admin/panel');
});

Auth::routes();



Route::get('/user/active/email/{token}','Admin\UserController@activation')->name('activation.account');


Route::get('/home', 'HomeController@index')->name('home');
Route::get('/admin/panel/athen', 'Admin\UserController@athenticationindex2')->name('users.athen');
Route::get('/admin/panel/usersecreport', 'Admin\UserController@usersecreport')->name('users.usersecreport');
Route::get('/admin/panel/modirsecreport', 'Admin\UserController@modirsecreport')->name('users.modirsecreport');
Route::get('/admin/panel/transaction', 'user\BuyController@transaction');
Route::get('/admin/panel/order', 'user\BuyController@order');
$this->get('/admin/panel/ticket', 'user\TicketController@index2');
$this->get('/admin/panel/sale', 'user\SaleController@indexadmin');
$this->get('/admin/panel/buy', 'user\BuyController@indexadmin');
$this->get('/admin/panel/voucher', 'user\VoucherController@indexadmin');
Route::delete('admin/panel/adminticket/{id}', 'user\TicketController@destroy2')->name('adminticket.delete');
Route::post('admin/panel/verify/{id}', 'user\TicketController@verify')->name('adminticket.verify');
Route::post('admin/panel/buyverify/{id}', 'user\BuyController@verify')->name('buy.verify');
Route::post('admin/panel/saleverify/{id}', 'user\SaleController@verify')->name('sale.verify');
Route::post('admin/panel/userverify/{id}', 'Admin\UserController@verify')->name('user.verify');
Route::post('admin/panel/userverify2/{id}', 'Admin\UserController@verify2')->name('user.verify2');
Route::get('/admin/panel/account', 'user\AccountInformationController@indexadmin');
Route::delete('/admin/panel/delaccount/{id}', 'user\AccountInformationController@destroy2')->name('delaccount');
Route::post('/admin/panel/verifyaccount/{id}', 'user\AccountInformationController@verifyaccount')->name('verifyaccount');
Route::delete('/admin/panel/adminsale/{id}', 'user\SaleController@destroy2')->name('adminsale.delete');
Route::delete('/admin/panel/adminbuy/{id}', 'user\BuyController@destroy2')->name('adminbuy.delete');
Route::post('/admin/panel/updatepass', 'Admin\UserController@updatepass')->name('users.updatepass');





Route::group(['namespace' => 'Admin'   ,  'middleware' => ['auth','checkAdmin'], 'prefix' => 'admin'],function () {
    $this->get('/panel', 'PanelController@index');
    $this->resource('/panel/users', 'UserController');
    $this->resource('/panel/modir', 'AdminController');
    $this->resource('/panel/setting', 'GeneralsettingController');
    $this->resource('/panel/managingcurrency' , 'ManagingCurrencyController');
    $this->resource('/panel/statusbuysale' , 'StatusBuySaleController');
    $this->resource('/panel/notifsetting' , 'NotifSettingController');
    $this::resource('/panel/bank' , 'BankController');
    });




$this->get('/user/panel', 'Admin\PanelController@index2');
Route::get('/user/panel/transaction', 'user\BuyController@transaction2');
Route::get('/user/panel/profile', 'Admin\UserController@profile');
Route::patch('/user/panel/profile', 'Admin\UserController@updateprofile')->name('profile.update');
Route::get('/user/panel/senddocuments', 'Admin\UserController@senddocuments');
Route::patch('/user/panel/senddocuments', 'Admin\UserController@updatesenddocuments')->name('senddocuments.update');;
Route::patch('/user/panel/updatesenddocuments', 'Admin\UserController@updatesenddocuments');
Route::get('/user/panel/resetpassword', 'Admin\UserController@resetpassword');
Route::post('/user/panel/salepayment', 'User\SaleController@payment')->name('salepayment');
Route::get('/user/panel/payment/checker', 'User\SaleController@checker');
Route::post('/user/panel/buypayment', 'User\BuyController@payment')->name('buypayment');
Route::get('/user/panel/payment/checker', 'User\BuyController@checker');
Route::post('/user/panel/voucherpayment', 'User\VoucherController@payment')->name('voucherpayment');
Route::get('/user/panel/payment/voucherpayment', 'User\VoucherController@checker');


Route::group(['namespace' => 'User'  , 'prefix' => 'user'],function () {

    $this->resource('/panel/userpanel', 'UserpanelController');
    $this->resource('/panel/ticket', 'TicketController');
    $this->resource('/panel/accountinformation', 'AccountInformationController');
    $this->resource('/panel/sale', 'SaleController');
    $this->resource('/panel/buy', 'BuyController');
    $this->resource('/panel/voucher', 'VoucherController');
});






Route::group(['namespace' => 'Auth'] , function (){
    // Authentication Routes...
    $this->get('login', 'LoginController@showLoginForm')->name('login');
    $this->post('login', 'LoginController@login');
    $this->get('logout', 'LoginController@logout')->name('logout');

    // Login And Register With Google
    // $this->get('login/google', 'LoginController@redirectToProvider');
    // $this->get('login/google/callback', 'LoginController@handleProviderCallback');
    // Registration Routes...
    $this->get('register', 'RegisterController@showRegistrationForm')->name('register');
    $this->post('register', 'RegisterController@register');

    // Password Reset Routes...
    $this->get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    $this->post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    $this->get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    $this->post('password/reset', 'ResetPasswordController@reset');
});

app/voucher.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class voucher extends Model
{
    //
    protected $fillable = [
        'user_id','voucher_type','voucher_number','voucher_code',
        'price_rial','price_arz','status',


    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\ActivationCode;
use App\admin;
use App\help;


use App\Http\Requests\UserRequest;
use App\User;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;


class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return string
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function index()
    {

        $users = User::latest()->paginate(5);
      //  $roles=['0'=>'کاربر' , '1'=> 'مدیر'];
     //  dd($users->toArray());
   return view('Admin.users.index', compact('users'));

    }



    /**
     * Show the form for creating a new resource.
     *
     * @return string
     */
    public function create()
    {

       return view('Admin.users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserRequest $request)
    {

        $user=$request->all();

        $user['password'] = bcrypt( $request->password );

        //dd($user);
        $user = User::create($user);
        alert()->success('', ' عملیات با موفقیت انجام شد ')->persistent('Close');
        return redirect(route('users.create'));


       //     return redirect('admin/users');


     //   $value=$request->all();
       //    dd($value);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\help  $help
     * @return \Illuminate\Http\Response
     */
    public function show(help $help)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\help  $help
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        //dd($user);
       // $user = User::get();
        return view('Admin.users.edit' , compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\help  $help
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {

        $user->update($request->all());


        return redirect(route('users.index'));

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\help $help
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(User $user)
    {

     //   die();
        $user->delete();
      //  $help->delete();
        return back();
    }

    public function athenticationindex2()
    {

        $users = User::latest()->paginate(5);
        //  dd($users->toArray());
        return view('Admin.users.index2', compact('users'));

    }
    public function usersecreport()
    {

        $users=User::where('level','0')->latest()->paginate(5);
        return view('Admin.users.usersecreport',compact('users'));

    }
    public function modirsecreport()
    {
        $users=User::where('level','1')->latest()->paginate(5);
        return view('Admin.users.modirsecreport' , compact('users'));

    }
    public function profile()
    {
        $user_id = auth()->user()->id;

        $value=User::where('id',$user_id)->get();

       // dd($value[0]);
        //$test='1';
        return view('user.user_profile.profile' , compact('value'));

    }
    public function updateprofile(Request $request , User $user)
    {

        $value=$request->all();
        $test=User::where('id',$value['id'])->get();

       $test[0]->update($value);

        // alert()->success('عملیات مورد نظر با موفقیت انجام شد','تایید شد');
        return back();


    }

    public function senddocuments()
    {
        $user_id = auth()->user()->id;

        $value=User::where('id',$user_id)->get();

        return view('user.user_profile.senddocuments' , compact('value'));

    }


    public function updatesenddocuments(Request $request, User $user)
    {
        $user_id = auth()->user()->id;

        $value=User::where('id',$user_id)->get();


        if ( $request->hasFile('imguser') ) {

            $FileNameimguser ='imguser'. time() . '.' . $request->file('imguser')->getClientOriginalExtension();

            if ($request->file('imguser')->move('assets/imguser', $FileNameimguser)) {

              //  dd($FileNameimguser);
                $value[0]['imguser']=$FileNameimguser;

            }

        }
        if ( $request->hasFile('imgnationalcard') ) {

            $FileNameimgnationalcard = 'imgnationalcard' . time() . '.' . $request->file('imgnationalcard')->getClientOriginalExtension();

            if ($request->file('imgnationalcard')->move('assets/imgnationalcard', $FileNameimgnationalcard)) {

               // dd($FileNameimgnationalcard);
                $value[0]['imgnationalcard']=$FileNameimgnationalcard;
                $value[0]['scan_national_code']='4';



            }
        }
        if ( $request->hasFile('imgidcard') ) {

            $FileNameimgidcard = 'imgidcard' . time() . '.' . $request->file('imgidcard')->getClientOriginalExtension();

            if ($request->file('imgidcard')->move('assets/imgidcard', $FileNameimgidcard)) {

             //   dd($FileNameimgidcard);
                $value[0]['imgidcard']=$FileNameimgidcard;
                $value[0]['scan_birth_certificate']='4';


            }
        }
        if ( $request->hasFile('imgbill') ) {

            $FileNameimgbill = 'imgbill' . time() . '.' . $request->file('imgbill')->getClientOriginalExtension();

            if ($request->file('imgbill')->move('assets/imgidcard', $FileNameimgbill)) {

              //  dd($FileNameimgbill);
                $value[0]['imgbill']=$FileNameimgbill;
                $value[0]['scane_bill']='4';



            }
        }
        //dd($value[0]);
        $value[0]->update(
            [
                'imguser' =>	 $FileNameimguser ,
                'imgnationalcard' => $FileNameimgnationalcard ,
                'imgidcard'=> $FileNameimgidcard ,
                'imgbill'=> $FileNameimgbill,
            ]);
        return back();

    }
    public function resetpassword()
    {

        return view('user.user_profile.resetpassword');

    }
    public function verify($id)
    {
        //  dd($id);
        $admin=User::find($id);
        $admin->update([
            'level'=>'1'
        ]);
        $value = admin::create([
            'user_id'=>$id
        ]);

        return back();

    }
    public function verify2($id)
    {
        //  dd($id);
        $value=User::find($id);
        $value->update([

            'scan_birth_certificate'=>'3',
            'scan_national_code'=>'3',
            'scane_bill'=>'3',
        ]);
        return back();

    }
    public function activation($token)
    {
        $activationcode=ActivationCode::whereCode($token)->first();

        if(! $activationcode)
        {
            dd('not exist');
            return redirect('/');
        }

        if($activationcode->expire < Carbon::now()){
            dd('expire');
            return redirect('/');
        }

        if($activationcode->used == 'true'){
            dd('used');
            return redirect('/');
        }

        $activationcode->user()->update([
            'active'=> 1
        ]);

        $activationcode->update([

            'used'=> true
        ]);

        auth()->loginUsingId($activationcode->user->id);
        return redirect('/');

    }
    public function updatepass(Request $request )
    {
       // $user=$request->all();
        $user_id=auth()->user()->id;
        $user=User::where('id',$user_id)->first();
       // dd($value);
        if($request->pass1 == $request->pass2)
        {
         //   $user['password'] = bcrypt( $request->pass1 );
            $user->update(
                [
                    'password' =>bcrypt( $request->pass1 )
                ]);
            //dd($user->toArray());
        }
        alert()->success('', ' پسورد با موفقیت تغییر یافت ')->persistent('Close');

        return back();

    }

}

app/Http/Controllers/User/TicketController.php
<?php

namespace App\Http\Controllers\user;

use App\Http\Controllers\Controller;
use App\Http\Requests\TicketRequest;
use App\ticket;
use Illuminate\Http\Request;

class TicketController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index2()
    {

        $tickets2=ticket::latest()->paginate(5);
      //  dd($tickets2);
        return view('Admin.ticket.index',compact('tickets2'));
    }
    public function index()
    {
        $user=auth()->user()->id;

        $tickets1=ticket::where('user_id',$user)->latest()->paginate(5);

        return view('user.ticket.index',compact('tickets1'));
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('user.ticket.sendticket');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TicketRequest $request)
    {



            $ticket=$request->all();


        if ( $request->hasFile('imgticket') ) {
            $FileName = time().'.'.$request->file('imgticket')->getClientOriginalExtension();
            if ( $request->file('imgticket')->move( 'assets/imageticket',$FileName ) ) {

              //  dd($FileName);

                $ticket['attached']=$FileName;
                $ticket['user_id']=auth()->user()->id;;

                $ticket['state']='0';

                $ticket = ticket::create($ticket);
                alert()->success('', ' تیکت ارسال شد ')->persistent('Close');
                return back();
            }



        }
        
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\ticket  $ticket
     * @return \Illuminate\Http\Response
     */
    public function show(ticket $ticket)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\ticket  $ticket
     * @return \Illuminate\Http\Response
     */
    public function edit(ticket $ticket)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\ticket  $ticket
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, ticket $ticket)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\ticket  $ticket
     * @return \Illuminate\Http\Response
     */
    public function destroy(ticket $ticket)
    {
        $tick=\App\ticket::find($ticket);
        //  dd($sale1->toArray());
        $tick[0]->delete();

        return back();
    }
    public function destroy2($id)
    {
      // dd($id);
        $ticket=ticket::find($id);
       $ticket->delete();
       return back();

    }
    public function verify($id)
    {
        //  dd($id);
        $ticket=ticket::find($id);
        $ticket->update([
            'state'=>'1'
        ]);
        return back();

    }
}

resources/views/user/voucher/listvoucher.blade.php
@extends('user.master')

@section('content')
    <div class="m-portlet m-portlet--tab">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <span class="m-portlet__head-icon m--hide">
                        <i class="la la-gear"></i>
                    </span>
                    <h3 class="m-portlet__head-text">
                        لیست ووچرها
                    </h3>
                </div>
            </div>
        </div>
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <div class="page-header head-section">
            <h2>

                </h2>
            <div class="btn-group">


            </div>
        </div>
        <div class="table-responsive">
            <table class="table table-striped table-bordered">
                <thead>
                <tr>
                    <th>شناسه</th>
                    <th>شماره ووچر</th>
                    <th>کد ووچر</th>
                    <th>مبلغ ریالی</th>
                    <th>مبلغ ارزی</th>
                    <th>تاریخ</th>
                    <th>وضعیت</th>

                </tr>
                </thead>
                <tbody>



                </tbody>
            </table>
        </div>
        <div style="text-align: center">

        </div>
    </div>
    </div>
@endsection

resources/views/user/voucher/voucher_buy.blade.php
@extends('user.master')

@section('script')

@endsection

@section('content')
    <div class="col-md-12">

        <!--begin::Portlet-->
        <div class="m-portlet m-portlet--tab">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                    <span class="m-portlet__head-icon m--hide">
                        <i class="la la-gear"></i>
                    </span>
                        <h3 class="m-portlet__head-text">
                            خرید ووچر پرفکت مانی
                        </h3>
                    </div>
                </div>
            </div>
    <div class="col-sm-12 col-sm-offset-3 col-md-6 col-md-offset-2 main" style="margin: 15px" >
        <div class="page-header head-section">

        </div>
        <form class="form-horizontal" action="{{ route('voucher.store') }}" method="post" enctype="multipart/form-data">
            {{ csrf_field() }}


            <div class="form-group">
                <div class="col-sm-12">
                    <label for="voucher_type" class="control-label">نوع ووچر</label>
                    <select name="voucher_type" id="voucher_type" class="form-control">
                        <option value="0" selected> 0</option>
                        <option value="1" selected>1</option>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-12">
                    <label for="voucher_number" class="control-label">تعداد ارز</label>
                    <input type="text" class="form-control" name="voucher_number" id="voucher_number" placeholder="تعداد خود را وارد نمایید" value="{{ old('currency_number') }}">
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-12">
                    <label for="" class="control-label">کارت بانکی</label>
                    <select name="" id="" class="form-control">
                        @foreach($cards as $card)

                            <option value={{ $i++ }} selected> {{ $card-> card_number }} </option>

                        @endforeach
                    </select>
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-12">
                    <label for="accountـreceived" class="control-label">حساب دریافتی</label>
                    <input type="text" class="form-control" name="accountـreceived" id="accountـreceived" placeholder="حساب ، کیف پول با آدرس الکترونیک جهت دریافت ارز" value="{{ old('accountـreceived') }}">
                </div>
            </div>



            <div class="form-group">
                <div class="col-sm-12">
                    <label for="total_price " class="control-label"> : قیمت کل</label>
                <!--   <input type="text" class="form-control" name="total_price " id="total_price " placeholder="حساب ، کیف پول با آدرس الکترونیک جهت دریافت ارز" value="{{ old('accountـreceived') }}">
                -->
                </div>

            </div>






            <div class="form-group">
                <div class="col-sm-12" style="padding: 20px">
                    <button type="submit" class="btn btn-danger">خرید و پرداخت</button>
                </div>
            </div>
        </form>
    </div>
        </div>
    </div>
@endsection